# Generated by Django 3.2.11 on 2022-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTimeLine',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('index', models.IntegerField(help_text='Entered number you want this object  be in what order', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
    ]
