# Generated by Django 3.2.11 on 2022-01-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_page_post',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
