# Generated by Django 3.2.2 on 2022-03-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date',
        ),
    ]
