# Generated by Django 3.2.11 on 2022-01-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_planned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
