# Generated by Django 3.2.2 on 2022-03-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_program_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='deadline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='lesson_start_time',
            field=models.IntegerField(),
        ),
    ]
