# Generated by Django 3.2.2 on 2022-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20220301_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='deadline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='lesson_start_time',
            field=models.CharField(max_length=255),
        ),
    ]
